import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'
import Topnav from '@/components/nav/topnav'
import {ClerkProvider} from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Head>
          <title>IP Solutions</title>
        </Head>
        <body className="{inter.className} bg-gray-50 font-sans">
        <Topnav />
          <div className='flex'>
            {children}
          </div>
        <footer className='pt-5 text-center items-center justify-center text-xs text-gray-400 font-bold m-3'>
          POWERED BY INVENIO POTENTIAL SDN BHD 2024</footer> 
        </body>
      </html>
    </ClerkProvider>
  )
}
